-- MySQL Script generated by MySQL Workbench
-- Sat 14 Jul 2018 12:46:16 PM WIB
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

/* SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0; */
/* SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0; */
/* SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES'; */


-- -----------------------------------------------------
-- Table `public`.`exchange_rate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS public.exchange_rate (
  currency_from VARCHAR(45) NOT NULL ,
  currency_to VARCHAR(45) NOT NULL ,
  create_date TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  modi_date TIMESTAMP(0) NULL ,
  PRIMARY KEY (currency_from, currency_to))
;


-- -----------------------------------------------------
-- Table `public`.`tx_exchange_rate`
-- -----------------------------------------------------
CREATE SEQUENCE public.tx_exchange_rate_seq;

CREATE TABLE IF NOT EXISTS public.tx_exchange_rate (
  seqno_tx BIGINT NOT NULL DEFAULT NEXTVAL ('public.tx_exchange_rate_seq') ,
  currency_from VARCHAR(45) NOT NULL ,
  currency_to VARCHAR(45) NOT NULL ,
  date DATE NOT NULL ,
  rate DOUBLE PRECISION NOT NULL ,
  create_date TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  modi_date TIMESTAMP(0) NULL ,
  PRIMARY KEY (seqno_tx),
  CONSTRAINT fk_tx_exchange_rate_exchange_rate
    FOREIGN KEY (currency_from , currency_to)
    REFERENCES public.exchange_rate (currency_from , currency_to)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
;

CREATE INDEX fk_tx_exchange_rate_exchange_rate_idx ON public.tx_exchange_rate (currency_from ASC, currency_to ASC);

CREATE UNIQUE INDEX unique_rate ON public.tx_exchange_rate (currency_from ASC, currency_to ASC, date ASC);


/* SET SQL_MODE=@OLD_SQL_MODE; */
/* SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS; */
/* SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS; */

-- DML
INSERT INTO public.exchange_rate
  (currency_from, currency_to, create_date, modi_date)
VALUES('USD', 'GDP', '2018-07-14 12:52:36.000', NULL);
INSERT INTO public.exchange_rate
  (currency_from, currency_to, create_date, modi_date)
VALUES('USD', 'IDR', '2018-07-14 13:10:20.000', NULL);

INSERT INTO public.tx_exchange_rate
  (seqno_tx, currency_from, currency_to, "date", rate, create_date, modi_date)
VALUES(9, 'USD', 'GDP', '2018-07-14', 0.759, '2018-07-14 12:52:38.000', '2018-07-14 12:52:40.000');
INSERT INTO public.tx_exchange_rate
  (seqno_tx, currency_from, currency_to, "date", rate, create_date, modi_date)
VALUES(15, 'USD', 'GDP', '2018-07-13', 0.7109, '2018-07-14 13:17:08.000', NULL);
INSERT INTO public.tx_exchange_rate
  (seqno_tx, currency_from, currency_to, "date", rate, create_date, modi_date)
VALUES(13, 'USD', 'GDP', '2018-07-01', 0.75799, '2018-07-14 13:06:14.000', '2018-07-18 14:10:25.000');

